#!/usr/bin/env python3
"""Turns every *.glsl here into a C string in ../ab_shaders_src.h (ab_shaders.c includes it).

Run it after changing a shader:  python3 frontend/ab/shaders/embed.py
The shaders must be ASCII (GLSL ES 1.00's character set) - the script refuses anything else.
"""
import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
out_path = os.path.join(here, '..', 'ab_shaders_src.h')

lines = ['/* generated by frontend/ab/shaders/embed.py from frontend/ab/shaders/*.glsl - do not edit */', '']
for name in sorted(os.listdir(here)):
    if not name.endswith('.glsl'):
        continue
    with open(os.path.join(here, name), 'rb') as f:
        data = f.read()
    try:
        text = data.decode('ascii')
    except UnicodeDecodeError:
        sys.exit('%s: not ASCII' % name)
    ident = 'ab_glsl_' + name[:-5].replace('-', '_')
    lines.append('static const char %s[] =' % ident)
    for line in text.replace('\r\n', '\n').split('\n'):
        esc = line.replace('\\', '\\\\').replace('"', '\\"').replace('\t', '    ')
        lines.append('  "%s\\n"' % esc)
    lines[-1] += ';'
    lines.append('')

with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(lines))
print('wrote', os.path.normpath(out_path))
